local P, U, T, R, L, W = game:GetService("Players"), game:GetService("UserInputService"), game:GetService("TweenService"), game:GetService("RunService"), game:GetService("Lighting"), game:GetService("Workspace")
local pl, gp, C = P.LocalPlayer, pl:WaitForChild("PlayerGui"), W.CurrentCamera
pcall(function() if gp:FindFirstChild("InfectiousRoot") then gp.InfectiousRoot:Destroy() end end)
local rt = Instance.new("ScreenGui"); rt.Name, rt.Parent, rt.ResetOnSpawn, rt.ZIndexBehavior, rt.IgnoreGuiInset = "InfectiousRoot", gp, false, Enum.ZIndexBehavior.Sibling, true
local bl = Instance.new("BlurEffect", L); bl.Size = 3
local th = {D={bg=Color3.fromRGB(18,18,22),ac=Color3.fromRGB(255,50,80),tx=Color3.fromRGB(220,220,230),bt=Color3.fromRGB(30,30,35),st=Color3.fromRGB(255,50,80)},C={bg=Color3.fromRGB(20,10,12),ac=Color3.fromRGB(255,30,50),tx=Color3.fromRGB(230,200,200),bt=Color3.fromRGB(35,20,22),st=Color3.fromRGB(200,30,50)},Cy={bg=Color3.fromRGB(8,10,20),ac=Color3.fromRGB(0,200,255),tx=Color3.fromRGB(180,230,255),bt=Color3.fromRGB(15,25,40),st=Color3.fromRGB(0,180,255)},A={bg=Color3.fromRGB(18,14,8),ac=Color3.fromRGB(255,180,0),tx=Color3.fromRGB(240,220,180),bt=Color3.fromRGB(30,25,15),st=Color3.fromRGB(200,150,0)},V={bg=Color3.fromRGB(16,10,22),ac=Color3.fromRGB(180,80,255),tx=Color3.fromRGB(220,200,240),bt=Color3.fromRGB(28,18,35),st=Color3.fromRGB(150,50,220)}}
local ct, io, im = "D", true, false
local dIA, dKA, dDA, dAH, dSA, dFL, dSQ, eA = false, false, false, false, false, false, false, false
local dI, dK, dDO, dAH2, dS, dF, dSQ2 = {}, {}, {}, {}, {}, {}, {}
local eO, eT = {}, nil
local function di(f, s) for _, v in pairs(f) do if v and v.Parent then table.insert(s, {Item=v,Parent=v.Parent}); pcall(function() v.Parent = nil end) end end end
local function ri(s) local c = 0; local tr = {}; for i, d in pairs(s) do if d and d.Item and not d.Item.Parent then pcall(function() if d.Parent and d.Parent ~= nil then d.Item.Parent = d.Parent else d.Item.Parent = W end; c = c + 1; table.insert(tr, i) end) else table.insert(tr, i) end end; table.sort(tr, function(a,b)return a>b end); for _, i in pairs(tr) do table.remove(s, i) end; return c end
local fr = Instance.new("Frame"); fr.Size, fr.Position, fr.BackgroundColor3, fr.BackgroundTransparency, fr.ClipsDescendants, fr.Parent, fr.Visible, fr.ZIndex, fr.Active = UDim2.new(0,280,0,230), UDim2.new(0.5,-140,0.5,-115), th.D.bg, 0.08, true, rt, true, 10, true
Instance.new("UICorner", fr).CornerRadius = UDim.new(0,8)
local st = Instance.new("UIStroke", fr); st.Color, st.Thickness, st.Transparency = th.D.st, 1.5, 0.6
local tb = Instance.new("Frame"); tb.Size, tb.BackgroundTransparency, tb.BackgroundColor3, tb.Parent, tb.Active = UDim2.new(1,0,0,32), 0.2, Color3.fromRGB(20,20,25), fr, true
Instance.new("UICorner", tb).CornerRadius = UDim.new(0,8)
local tl = Instance.new("TextLabel"); tl.Size, tl.Position, tl.Text, tl.TextColor3, tl.TextSize, tl.Font, tl.TextXAlignment, tl.BackgroundTransparency, tl.Parent = UDim2.new(0.5,0,1,0), UDim2.new(0,8,0,0), "NZ-IS", th.D.ac, 14, Enum.Font.GothamBold, Enum.TextXAlignment.Left, 1, tb
local mn = Instance.new("TextButton"); mn.Size, mn.Position, mn.Text, mn.TextColor3, mn.TextSize, mn.Font, mn.BackgroundColor3, mn.BackgroundTransparency, mn.Parent, mn.AutoButtonColor = UDim2.new(0,26,0,26), UDim2.new(1,-62,0,3), "─", Color3.fromRGB(200,200,210), 16, Enum.Font.GothamBold, Color3.fromRGB(40,40,45), 0.2, tb, true
Instance.new("UICorner", mn).CornerRadius = UDim.new(0,5)
local cl = Instance.new("TextButton"); cl.Size, cl.Position, cl.Text, cl.TextColor3, cl.TextSize, cl.Font, cl.BackgroundColor3, cl.BackgroundTransparency, cl.Parent, cl.AutoButtonColor = UDim2.new(0,26,0,26), UDim2.new(1,-34,0,3), "X", Color3.fromRGB(200,200,210), 13, Enum.Font.GothamBold, Color3.fromRGB(40,40,45), 0.2, tb, true
Instance.new("UICorner", cl).CornerRadius = UDim.new(0,5)
local mf = Instance.new("TextButton"); mf.Size, mf.Position, mf.Text, mf.TextColor3, mf.TextSize, mf.Font, mf.BackgroundColor3, mf.BackgroundTransparency, mf.Parent, mf.Visible, mf.ZIndex, mf.AutoButtonColor = UDim2.new(0,50,0,50), UDim2.new(1,-60,0,10), "NZ", Color3.fromRGB(255,255,255), 13, Enum.Font.GothamBold, th.D.ac, 0.15, rt, false, 999, true
Instance.new("UICorner", mf).CornerRadius = UDim.new(0,12); Instance.new("UIStroke", mf).Color = th.D.ac
local rb = Instance.new("TextButton"); rb.Size, rb.Position, rb.Text, rb.TextSize, rb.TextColor3, rb.BackgroundColor3, rb.BackgroundTransparency, rb.Parent, rb.Visible, rb.ZIndex, rb.AutoButtonColor = UDim2.new(0,50,0,50), UDim2.new(0,10,1,-65), "▶", 22, Color3.fromRGB(255,255,255), Color3.fromRGB(50,200,100), 0.2, rt, false, 999, true
Instance.new("UICorner", rb).CornerRadius = UDim.new(1,0); Instance.new("UIStroke", rb).Color = Color3.fromRGB(255,255,255)
local tc = Instance.new("Frame"); tc.Size, tc.Position, tc.BackgroundTransparency, tc.Parent = UDim2.new(1,-10,0,26), UDim2.new(0,5,0,35), 1, fr
local function ct2(n, x) local b = Instance.new("TextButton"); b.Size, b.Position, b.Text, b.TextColor3, b.TextSize, b.Font, b.BackgroundColor3, b.BackgroundTransparency, b.Parent, b.AutoButtonColor = UDim2.new(0,85,1,0), UDim2.new(0,x,0,0), n, Color3.fromRGB(200,200,210), 10, Enum.Font.GothamBold, Color3.fromRGB(30,30,35), 0.3, tc, true; Instance.new("UICorner", b).CornerRadius = UDim.new(0,5); return b end
local tm, tth, to = ct2("Mods",0), ct2("Theme",90), ct2("Others",180)
local function cp() local p = Instance.new("ScrollingFrame"); p.Size, p.Position, p.BackgroundTransparency, p.CanvasSize, p.ScrollBarThickness, p.ScrollBarImageColor3, p.Parent, p.Visible = UDim2.new(1,-10,1,-74), UDim2.new(0,5,0,65), 1, UDim2.new(0,0,0,310), 3, th.D.ac, fr, false; return p end
local mp, tpg, op = cp(), cp(), cp()
local function ml(t, y, p, w) w = w or 100; local l = Instance.new("TextLabel"); l.Size, l.Position, l.Text, l.TextColor3, l.TextSize, l.Font, l.BackgroundTransparency, l.TextXAlignment, l.Parent = UDim2.new(0,w,0,22), UDim2.new(0,0,0,y), t, th.D.tx, 11, Enum.Font.Gotham, 1, Enum.TextXAlignment.Left, p; return l end
local function mt(y, p) local b = Instance.new("TextButton"); b.Size, b.Position, b.Text, b.TextColor3, b.TextSize, b.Font, b.BackgroundColor3, b.Parent, b.AutoButtonColor = UDim2.new(0,60,0,22), UDim2.new(0,160,0,y), "OFF", Color3.fromRGB(255,100,100), 10, Enum.Font.GothamBold, Color3.fromRGB(40,20,20), p, true; Instance.new("UICorner", b).CornerRadius = UDim.new(0,4); return b end
local function mb(t, y, p, c) c = c or Color3.fromRGB(60,30,30); local b = Instance.new("TextButton"); b.Size, b.Position, b.Text, b.TextColor3, b.TextSize, b.Font, b.BackgroundColor3, b.Parent, b.AutoButtonColor = UDim2.new(0,140,0,30), UDim2.new(0.5,-70,0,y), t, Color3.fromRGB(255,255,255), 12, Enum.Font.GothamBold, c, p, true; Instance.new("UICorner", b).CornerRadius = UDim.new(0,6); return b end
local yOff = 4; ml("Delete Infected", yOff, mp, 110); local iB = mt(yOff, mp); yOff = yOff + 28; ml("Disable Kill", yOff, mp, 110); local kB = mt(yOff, mp); yOff = yOff + 28; ml("Disable Doors/Gates", yOff, mp, 110); local dB = mt(yOff, mp); yOff = yOff + 28; ml("Disable Anti-Hack", yOff, mp, 110); local aB = mt(yOff, mp); yOff = yOff + 28; ml("Disable Spears", yOff, mp, 110); local sB = mt(yOff, mp); yOff = yOff + 28; ml("Disable Fire/Lava", yOff, mp, 110); local fB = mt(yOff, mp); yOff = yOff + 28; ml("Disable SeismicRockWall", yOff, mp, 110); local sqB = mt(yOff, mp); yOff = yOff + 28; ml("TEAM ESP", yOff, mp, 110); local eB = mt(yOff, mp); yOff = yOff + 32; local sL = Instance.new("TextLabel"); sL.Size, sL.Position, sL.Text, sL.TextColor3, sL.TextSize, sL.Font, sL.BackgroundTransparency, sL.TextXAlignment, sL.Parent = UDim2.new(1,-10,0,22), UDim2.new(0,0,0,yOff), "Status: Ready", Color3.fromRGB(0,255,150), 11, Enum.Font.GothamBold, 1, Enum.TextXAlignment.Left, mp; yOff = yOff + 28; mp.CanvasSize = UDim2.new(0,0,0,yOff+10)
local tY = 8; local tL = Instance.new("TextLabel"); tL.Size, tL.Position, tL.Text, tL.TextColor3, tL.TextSize, tL.Font, tL.BackgroundTransparency, tL.TextXAlignment, tL.Parent = UDim2.new(1,-10,0,24), UDim2.new(0,0,0,tY), "SELECT THEME", Color3.fromRGB(180,180,220), 12, Enum.Font.GothamBold, 1, Enum.TextXAlignment.Left, tpg; tY = tY + 30
local function mtb(n, y, c) local b = Instance.new("TextButton"); b.Size, b.Position, b.Text, b.TextColor3, b.TextSize, b.Font, b.BackgroundColor3, b.Parent, b.AutoButtonColor = UDim2.new(0,120,0,28), UDim2.new(0,0,0,y), n, Color3.fromRGB(255,255,255), 12, Enum.Font.GothamBold, c or Color3.fromRGB(30,30,50), tpg, true; Instance.new("UICorner", b).CornerRadius = UDim.new(0,5); b.MouseButton1Click:Connect(function() ct = n; local t = th[n]; fr.BackgroundColor3, st.Color, tl.TextColor3, sL.TextColor3, mf.BackgroundColor3, Instance.new("UIStroke", mf).Color, rb.BackgroundColor3 = t.bg, t.st, t.ac, t.ac, t.ac, t.ac, t.ac; for _, ch in pairs(fr:GetDescendants()) do if ch:IsA("TextButton") and ch ~= iB and ch ~= kB and ch ~= dB and ch ~= aB and ch ~= sB and ch ~= fB and ch ~= sqB and ch ~= eB and ch ~= mn and ch ~= cl then if ch.Text == "Mods" or ch.Text == "Theme" or ch.Text == "Others" then ch.TextColor3 = t.ac end end; if ch:IsA("ScrollingFrame") then ch.ScrollBarImageColor3 = t.ac end end; cl.BackgroundColor3, mn.BackgroundColor3, mn.TextColor3 = t.bt, t.bt, t.ac end); b.TouchTap:Connect(function() ct = n; local t = th[n]; fr.BackgroundColor3, st.Color, tl.TextColor3, sL.TextColor3, mf.BackgroundColor3, Instance.new("UIStroke", mf).Color, rb.BackgroundColor3 = t.bg, t.st, t.ac, t.ac, t.ac, t.ac, t.ac; for _, ch in pairs(fr:GetDescendants()) do if ch:IsA("TextButton") and ch ~= iB and ch ~= kB and ch ~= dB and ch ~= aB and ch ~= sB and ch ~= fB and ch ~= sqB and ch ~= eB and ch ~= mn and ch ~= cl then if ch.Text == "Mods" or ch.Text == "Theme" or ch.Text == "Others" then ch.TextColor3 = t.ac end end; if ch:IsA("ScrollingFrame") then ch.ScrollBarImageColor3 = t.ac end end; cl.BackgroundColor3, mn.BackgroundColor3, mn.TextColor3 = t.bt, t.bt, t.ac end); return b end
local tC = {{n="Default",c=Color3.fromRGB(30,20,25)},{n="Crimson",c=Color3.fromRGB(35,15,20)},{n="Cyber",c=Color3.fromRGB(10,15,40)},{n="Amber",c=Color3.fromRGB(35,25,15)},{n="Violet",c=Color3.fromRGB(25,15,40)}}
for _, t in pairs(tC) do mtb(t.n, tY, t.c); tY = tY + 34 end
local oY = 20; local dBt = mb("Destroy GUI", oY, op, Color3.fromRGB(80,20,20)); oY = oY + 40; local cL = Instance.new("TextLabel"); cL.Size, cL.Position, cL.Text, cL.TextColor3, cL.TextSize, cL.Font, cL.BackgroundTransparency, cL.TextXAlignment, cL.Parent = UDim2.new(1,-10,0,20), UDim2.new(0,0,0,oY), "NZ-IS v6", Color3.fromRGB(100,100,120), 10, Enum.Font.Gotham, 1, Enum.TextXAlignment.Center, op; oY = oY + 30; op.CanvasSize = UDim2.new(0,0,0,oY+10)
local function swM() mp.Visible, tpg.Visible, op.Visible, tm.TextColor3, tth.TextColor3, to.TextColor3 = true, false, false, th[ct].ac, Color3.fromRGB(180,180,210), Color3.fromRGB(180,180,210) end
local function swT() mp.Visible, tpg.Visible, op.Visible, tth.TextColor3, tm.TextColor3, to.TextColor3 = false, true, false, th[ct].ac, Color3.fromRGB(180,180,210), Color3.fromRGB(180,180,210) end
local function swO() mp.Visible, tpg.Visible, op.Visible, to.TextColor3, tm.TextColor3, tth.TextColor3 = false, false, true, th[ct].ac, Color3.fromRGB(180,180,210), Color3.fromRGB(180,180,210) end
tm.MouseButton1Click:Connect(swM); tm.TouchTap:Connect(swM); tth.MouseButton1Click:Connect(swT); tth.TouchTap:Connect(swT); to.MouseButton1Click:Connect(swO); to.TouchTap:Connect(swO); mp.Visible, tm.TextColor3 = true, th.D.ac
local function mng() if im then return end; im = true; fr.Visible, mf.Visible, rb.Visible, bl.Size = false, true, false, 0 end
local function umng() if not im then return end; im = false; fr.Visible, mf.Visible, bl.Size = true, false, 3 end
mn.MouseButton1Click:Connect(function() if im then umng() else mng() end end); mn.TouchTap:Connect(function() if im then umng() else mng() end end); mf.MouseButton1Click:Connect(umng); mf.TouchTap:Connect(umng); mf.InputBegan:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then umng() end end)
local function togOC() if io then io, fr.Visible, mf.Visible, rb.Visible, cl.Text, cl.TextColor3, bl.Size = false, false, false, true, "▶", Color3.fromRGB(100,255,100), 0 else io, fr.Visible, rb.Visible, cl.Text, cl.TextColor3 = true, true, false, "X", Color3.fromRGB(200,200,210); if not im then bl.Size = 3 end end end
cl.MouseButton1Click:Connect(togOC); cl.TouchTap:Connect(togOC)
rb.MouseButton1Click:Connect(function() if not io then io, fr.Visible, rb.Visible, cl.Text, cl.TextColor3 = true, true, false, "X", Color3.fromRGB(200,200,210); if not im then bl.Size = 3 end end end); rb.TouchTap:Connect(function() if not io then io, fr.Visible, rb.Visible, cl.Text, cl.TextColor3 = true, true, false, "X", Color3.fromRGB(200,200,210); if not im then bl.Size = 3 end end end)
local fD = {isDragging=false,startPos=nil,frameStart=nil,hasMoved=false}
tb.InputBegan:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then fD.isDragging, fD.hasMoved, fD.startPos, fD.frameStart = false, false, i.Position, fr.Position end end)
tb.InputChanged:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseMovement or i.UserInputType == Enum.UserInputType.Touch then if fD.startPos then local d = i.Position - fD.startPos; if math.sqrt(d.X^2+d.Y^2) > 5 then fD.hasMoved, fD.isDragging = true, true end; if fD.isDragging then fr.Position = UDim2.new(fD.frameStart.X.Scale, fD.frameStart.X.Offset + d.X, fD.frameStart.Y.Scale, fD.frameStart.Y.Offset + d.Y) end end end end)
tb.InputEnded:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then fD.isDragging, fD.startPos, fD.frameStart = false, nil, nil end end)
local rD = {isDragging=false,startPos=nil,btnStart=nil,hasMoved=false}
rb.InputBegan:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then rD.isDragging, rD.hasMoved, rD.startPos, rD.btnStart = false, false, i.Position, rb.Position end end)
rb.InputChanged:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseMovement or i.UserInputType == Enum.UserInputType.Touch then if rD.startPos then local d = i.Position - rD.startPos; if math.sqrt(d.X^2+d.Y^2) > 10 then rD.hasMoved, rD.isDragging = true, true end; if rD.isDragging then rb.Position = UDim2.new(rD.btnStart.X.Scale, rD.btnStart.X.Offset + d.X, rD.btnStart.Y.Scale, rD.btnStart.Y.Offset + d.Y) end end end end)
rb.InputEnded:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then rD.isDragging, rD.startPos, rD.btnStart = false, nil, nil end end)
U.InputBegan:Connect(function(i, gp2) if gp2 then return end; if i.KeyCode == Enum.KeyCode.Insert then if im then umng() else mng() end end end)
local function gTC(p2) if p2.Team then return p2.Team.TeamColor.Color end; return Color3.fromRGB(255,255,255) end
local function cE(tg)
if tg == pl then return end; if not tg.Character or not tg.Character:FindFirstChild("HumanoidRootPart") then return end
local rp = tg.Character.HumanoidRootPart; local tc = gTC(tg); if eO[tg] then pcall(function() if eO[tg].H then eO[tg].H:Destroy() end; if eO[tg].B then eO[tg].B:Destroy() end; if eO[tg].N then eO[tg].N:Destroy() end; if eO[tg].L then eO[tg].L:Destroy() end end); eO[tg] = nil end
local h = Instance.new("Highlight"); h.FillTransparency, h.OutlineTransparency, h.FillColor, h.OutlineColor, h.DepthMode, h.Parent = 0.5, 0.2, tc, tc, Enum.HighlightDepthMode.AlwaysOnTop, tg.Character
local b = Instance.new("Frame"); b.Size, b.Position, b.BackgroundTransparency, b.BackgroundColor3, b.BorderSizePixel, b.BorderColor3, b.Parent, b.Visible, b.ZIndex = UDim2.new(0,30,0,60), UDim2.new(0.5,-15,0.5,-30), 0.3, tc, 2, tc, rt, true, 999
local nl = Instance.new("TextLabel"); nl.Size, nl.Position, nl.Text, nl.TextColor3, nl.TextSize, nl.Font, nl.BackgroundTransparency, nl.TextStrokeColor3, nl.TextStrokeTransparency, nl.TextXAlignment, nl.Parent, nl.Visible, nl.ZIndex = UDim2.new(0,150,0,20), UDim2.new(0.5,-75,0.5,-50), tg.Name, tc, 14, Enum.Font.GothamBold, 1, Color3.fromRGB(0,0,0), 0.2, Enum.TextXAlignment.Center, rt, true, 999
local l = Instance.new("Frame"); l.Size, l.BackgroundTransparency, l.BackgroundColor3, l.Parent, l.Visible, l.ZIndex = UDim2.new(0,1,0,1), 0.4, tc, rt, true, 999
eO[tg] = {H=h, B=b, N=nl, L=l, R=rp, C=tg.Character}
end
local function uE()
if not eA then for _, d in pairs(eO) do pcall(function() if d.H then d.H:Destroy() end; if d.B then d.B:Destroy() end; if d.N then d.N:Destroy() end; if d.L then d.L:Destroy() end end) end; eO = {}; return end
local c = pl.Character; if not c or not c:FindFirstChild("HumanoidRootPart") then return end; local mp2 = c.HumanoidRootPart.Position; local mr = c.HumanoidRootPart
for _, tg in pairs(P:GetPlayers()) do if tg == pl then if eO[pl] == nil then local sl = Instance.new("Frame"); sl.Size, sl.BackgroundTransparency, sl.BackgroundColor3, sl.Parent, sl.Visible, sl.ZIndex = UDim2.new(0,1,0,1), 0.4, gTC(pl), rt, true, 999; eO[pl] = {L=sl, R=mr, C=c} end; if eO[pl] and eO[pl].L and mr then local sp, os = C:WorldToViewportPoint(mr.Position); if os then local sc = Vector2.new(C.ViewportSize.X/2, C.ViewportSize.Y); local dx, dy = sp.X - sc.X, sp.Y - sc.Y; local a = math.atan2(dy, dx); local len = math.clamp(math.sqrt(dx^2+dy^2), 20, 300); eO[pl].L.Size, eO[pl].L.Position, eO[pl].L.Rotation, eO[pl].L.BackgroundTransparency, eO[pl].L.Visible = UDim2.new(0,len,0,2), UDim2.new(0,sc.X,0,sc.Y), math.deg(a), 0.3, true end end; goto cont end
if tg.Character and tg.Character:FindFirstChild("HumanoidRootPart") then if not eO[tg] or eO[tg].C ~= tg.Character then cE(tg) end; local d = eO[tg]; if d and d.R then local tp = d.R.Position; local dist = (mp2 - tp).Magnitude; local sp, os = C:WorldToViewportPoint(tp); if os then local bs = math.clamp(80/dist, 20, 80); d.B.Size, d.B.Position, d.B.BackgroundTransparency, d.B.Visible = UDim2.new(0,bs,0,bs*1.8), UDim2.new(0,sp.X-bs/2,0,sp.Y-bs*0.9), 0.3, true; d.N.Position = UDim2.new(0,sp.X-75,0,sp.Y-bs*1.1-20); d.N.Visible = true; d.H.FillTransparency, d.H.OutlineTransparency = 0.5, 0.2; local cx, cy = sp.X, sp.Y + bs*0.5; local sc = Vector2.new(C.ViewportSize.X/2, C.ViewportSize.Y); local dx, dy = cx - sc.X, cy - sc.Y; local a = math.atan2(dy, dx); local len = math.clamp(math.sqrt(dx^2+dy^2), 20, 300); d.L.Size, d.L.Position, d.L.Rotation, d.L.BackgroundTransparency, d.L.Visible = UDim2.new(0,len,0,2), UDim2.new(0,sc.X,0,sc.Y), math.deg(a), 0.3, true else d.B.Visible, d.N.Visible, d.L.Visible, d.H.FillTransparency, d.H.OutlineTransparency = false, false, false, 0.5, 0.2 end end end; ::cont:: end
end
local function tE()
eA = not eA
if eA then eB.Text, eB.BackgroundColor3, eB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "ESP ENABLED", Color3.fromRGB(0,200,255)
if eC then pcall(function() eC:Disconnect() end); eC = nil end; if eT then pcall(function() eT:Disconnect() end); eT = nil end
for _, tg in pairs(P:GetPlayers()) do if tg ~= pl then cE(tg) end end
eC = R.RenderStepped:Connect(uE); eT = R.Heartbeat:Connect(function() if eA then for _, tg in pairs(P:GetPlayers()) do if tg ~= pl then if not eO[tg] or eO[tg].C ~= tg.Character then cE(tg) end end end end end)
P.PlayerAdded:Connect(function(tg) task.wait(0.5); if eA then cE(tg) end end)
P.PlayerRemoving:Connect(function(tg) if eO[tg] then pcall(function() if eO[tg].H then eO[tg].H:Destroy() end; if eO[tg].B then eO[tg].B:Destroy() end; if eO[tg].N then eO[tg].N:Destroy() end; if eO[tg].L then eO[tg].L:Destroy() end end); eO[tg] = nil end end)
else eB.Text, eB.BackgroundColor3, eB.TextColor3, sL.Text, sL.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100), "ESP DISABLED", Color3.fromRGB(255,100,100)
if eC then pcall(function() eC:Disconnect() end); eC = nil end; if eT then pcall(function() eT:Disconnect() end); eT = nil end
for _, d in pairs(eO) do pcall(function() if d.H then d.H:Destroy() end; if d.B then d.B:Destroy() end; if d.N then d.N:Destroy() end; if d.L then d.L:Destroy() end end) end; eO = {}; task.wait(0.5); sL.Text, sL.TextColor3 = "Ready", Color3.fromRGB(0,255,150) end
end
eB.MouseButton1Click:Connect(tE); eB.TouchTap:Connect(tE)
local function tI() dIA = not dIA; if dIA then iB.Text, iB.BackgroundColor3, iB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "Scanning...", Color3.fromRGB(0,255,100); local f = {}; for _, v in pairs(W:GetDescendants()) do if v:IsA("BasePart") or v:IsA("Model") or v:IsA("Folder") or v:IsA("Script") or v:IsA("LocalScript") or v:IsA("ModuleScript") then if v.Name and string.lower(v.Name):find("infect") then table.insert(f, v) end end end; di(f, dI); if #f > 0 then sL.Text, sL.TextColor3 = "Deleted "..#f.." infected", Color3.fromRGB(255,200,50) else sL.Text, sL.TextColor3 = "No infected found", Color3.fromRGB(0,255,150) end else iB.Text, iB.BackgroundColor3, iB.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100); local c = ri(dI); sL.Text = c > 0 and "Restored "..c.." infected" or "No infected to restore"; sL.TextColor3 = Color3.fromRGB(0,255,150) end end
iB.MouseButton1Click:Connect(tI); iB.TouchTap:Connect(tI)
local function tK() dKA = not dKA; if dKA then kB.Text, kB.BackgroundColor3, kB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "Scanning...", Color3.fromRGB(0,255,100); local f = {}; for _, v in pairs(W:GetDescendants()) do if v:IsA("BasePart") or v:IsA("Model") or v:IsA("Folder") or v:IsA("Script") or v:IsA("LocalScript") or v:IsA("ModuleScript") then if v.Name and string.lower(v.Name):find("kill") then table.insert(f, v) end end end; di(f, dK); if #f > 0 then sL.Text, sL.TextColor3 = "Deleted "..#f.." kill items", Color3.fromRGB(255,200,50) else sL.Text, sL.TextColor3 = "No kill items found", Color3.fromRGB(0,255,150) end else kB.Text, kB.BackgroundColor3, kB.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100); local c = ri(dK); sL.Text = c > 0 and "Restored "..c.." kill items" or "No kill items to restore"; sL.TextColor3 = Color3.fromRGB(0,255,150) end end
kB.MouseButton1Click:Connect(tK); kB.TouchTap:Connect(tK)
local function tD() dDA = not dDA; if dDA then dB.Text, dB.BackgroundColor3, dB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "Scanning...", Color3.fromRGB(0,255,100); local f, kw = {}, {"door","gate","portal","doorway","entrance","exit"}; for _, v in pairs(W:GetDescendants()) do if v:IsA("BasePart") or v:IsA("Model") or v:IsA("Folder") or v:IsA("Script") or v:IsA("LocalScript") or v:IsA("ModuleScript") and v.Name then local nl = string.lower(v.Name); for _, k in pairs(kw) do if nl:find(k) then table.insert(f, v); break end end end end; di(f, dDO); if #f > 0 then sL.Text, sL.TextColor3 = "Deleted "..#f.." doors/gates", Color3.fromRGB(255,200,50) else sL.Text, sL.TextColor3 = "No doors/gates found", Color3.fromRGB(0,255,150) end else dB.Text, dB.BackgroundColor3, dB.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100); local c = ri(dDO); sL.Text = c > 0 and "Restored "..c.." doors/gates" or "No doors/gates to restore"; sL.TextColor3 = Color3.fromRGB(0,255,150) end end
dB.MouseButton1Click:Connect(tD); dB.TouchTap:Connect(tD)
local function tAH() dAH = not dAH; if dAH then aB.Text, aB.BackgroundColor3, aB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "Scanning...", Color3.fromRGB(0,255,100); local f, kw = {}, {"anti","hack","anticheat","anti-cheat","cheat","exploit","bypass","security"}; for _, v in pairs(W:GetDescendants()) do if v:IsA("BasePart") or v:IsA("Model") or v:IsA("Folder") or v:IsA("Script") or v:IsA("LocalScript") or v:IsA("ModuleScript") and v.Name then local nl = string.lower(v.Name); for _, k in pairs(kw) do if nl:find(k) then table.insert(f, v); break end end end end; di(f, dAH2); if #f > 0 then sL.Text, sL.TextColor3 = "Deleted "..#f.." anti-hack items", Color3.fromRGB(255,200,50) else sL.Text, sL.TextColor3 = "No anti-hack items found", Color3.fromRGB(0,255,150) end else aB.Text, aB.BackgroundColor3, aB.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100); local c = ri(dAH2); sL.Text = c > 0 and "Restored "..c.." anti-hack items" or "No anti-hack items to restore"; sL.TextColor3 = Color3.fromRGB(0,255,150) end end
aB.MouseButton1Click:Connect(tAH); aB.TouchTap:Connect(tAH)
local function tS() dSA = not dSA; if dSA then sB.Text, sB.BackgroundColor3, sB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "Scanning...", Color3.fromRGB(0,255,100); local f, kw = {}, {"spear","javelin","lance","pike","harpoon"}; for _, v in pairs(W:GetDescendants()) do if v:IsA("BasePart") or v:IsA("Model") or v:IsA("Folder") or v:IsA("Script") or v:IsA("LocalScript") or v:IsA("ModuleScript") and v.Name then local nl = string.lower(v.Name); for _, k in pairs(kw) do if nl:find(k) then table.insert(f, v); break end end end end; di(f, dS); if #f > 0 then sL.Text, sL.TextColor3 = "Deleted "..#f.." spears", Color3.fromRGB(255,200,50) else sL.Text, sL.TextColor3 = "No spears found", Color3.fromRGB(0,255,150) end else sB.Text, sB.BackgroundColor3, sB.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100); local c = ri(dS); sL.Text = c > 0 and "Restored "..c.." spears" or "No spears to restore"; sL.TextColor3 = Color3.fromRGB(0,255,150) end end
sB.MouseButton1Click:Connect(tS); sB.TouchTap:Connect(tS)
local function tF() dFL = not dFL; if dFL then fB.Text, fB.BackgroundColor3, fB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "Scanning...", Color3.fromRGB(0,255,100); local f, kw = {}, {"fire","lava","flame","burn","ignite","molten","magma","combust","pyro"}; for _, v in pairs(W:GetDescendants()) do if v:IsA("BasePart") or v:IsA("Model") or v:IsA("Folder") or v:IsA("Script") or v:IsA("LocalScript") or v:IsA("ModuleScript") and v.Name then local nl = string.lower(v.Name); for _, k in pairs(kw) do if nl:find(k) then table.insert(f, v); break end end end end; di(f, dF); if #f > 0 then sL.Text, sL.TextColor3 = "Deleted "..#f.." fire/lava items", Color3.fromRGB(255,200,50) else sL.Text, sL.TextColor3 = "No fire/lava items found", Color3.fromRGB(0,255,150) end else fB.Text, fB.BackgroundColor3, fB.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100); local c = ri(dF); sL.Text = c > 0 and "Restored "..c.." fire/lava items" or "No fire/lava items to restore"; sL.TextColor3 = Color3.fromRGB(0,255,150) end end
fB.MouseButton1Click:Connect(tF); fB.TouchTap:Connect(tF)
local function tSQ() dSQ = not dSQ; if dSQ then sqB.Text, sqB.BackgroundColor3, sqB.TextColor3, sL.Text, sL.TextColor3 = "ON", Color3.fromRGB(20,60,30), Color3.fromRGB(100,255,100), "Scanning...", Color3.fromRGB(0,255,100); local f, kw = {}, {"weight","seismic","rockwall","rock_wall","seismicwall","weighted"}; for _, v in pairs(W:GetDescendants()) do if v:IsA("Model") and v.Name then local nl = string.lower(v.Name); for _, k in pairs(kw) do if nl:find(k) then table.insert(f, v); break end end end end; di(f, dSQ2); if #f > 0 then sL.Text, sL.TextColor3 = "Deleted "..#f.." seismic rock walls", Color3.fromRGB(255,200,50) else sL.Text, sL.TextColor3 = "No seismic rock walls found", Color3.fromRGB(0,255,150) end else sqB.Text, sqB.BackgroundColor3, sqB.TextColor3 = "OFF", Color3.fromRGB(40,20,20), Color3.fromRGB(255,100,100); local c = ri(dSQ2); sL.Text = c > 0 and "Restored "..c.." seismic rock walls" or "No seismic rock walls to restore"; sL.TextColor3 = Color3.fromRGB(0,255,150) end end
sqB.MouseButton1Click:Connect(tSQ); sqB.TouchTap:Connect(tSQ)
local function dG() if eC then pcall(function() eC:Disconnect() end); eC = nil end; if eT then pcall(function() eT:Disconnect() end); eT = nil end; for _, d in pairs(eO) do pcall(function() if d.H then d.H:Destroy() end; if d.B then d.B:Destroy() end; if d.N then d.N:Destroy() end; if d.L then d.L:Destroy() end end) end; eO = {}; rt:Destroy(); bl:Destroy() end
dBt.MouseButton1Click:Connect(dG); dBt.TouchTap:Connect(dG)
fr.BackgroundTransparency, fr.Size = 1, UDim2.new(0,0,0,0); T:Create(fr, TweenInfo.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {Size = UDim2.new(0,280,0,230), BackgroundTransparency = 0.08}):Play(); bl.Size = 3
print("NZ-IS v6 - LOADED!")
